from django.urls import path

from serialization_app.views import (
    create_book,
    create_books,
    create_department,
    create_employee,
    create_hex_nut,
    create_product,
    create_store,
    create_user,
    create_workstation,
    get_book,
    get_books,
    get_hex_nut,
    get_hex_nuts,
    get_product,
    get_products,
    get_store,
    get_stores,
    get_user,
    get_users,
    get_workstation,
    get_workstations,
    partial_update_store,
    update_book,
    update_books,
    update_department,
    update_employee,
    update_hex_nut,
    update_product,
    update_store,
    update_user,
    update_workstation,
)

urlpatterns = [
    path("hex-nuts/get", get_hex_nuts, name="get-hex-nuts"),
    path("hex-nuts/<int:id>/get", get_hex_nut, name="get-hex-nut"),
    path("hex-nuts/create", create_hex_nut, name="create-hex-nuts"),
    path("hex-nuts/<int:id>/update", update_hex_nut, name="update-hex-nut"),
    path("workstations/get", get_workstations, name="get-workstations"),
    path("workstations/<int:id>/get", get_workstation, name="get-workstation"),
    path("workstations/create", create_workstation, name="create-workstation"),
    path("workstations/<int:id>/update", update_workstation, name="update-workstation"),
    path("stores/get", get_stores, name="get-stores"),
    path("stores/<int:id>/get", get_store, name="get-store"),
    path("stores/create", create_store, name="create-store"),
    path("stores/<int:id>/update", update_store, name="update-store"),
    path(
        "stores/<int:id>/partial-update",
        partial_update_store,
        name="partial-update-store",
    ),
    path("products/get", get_products, name="get-products"),
    path("products/<int:id>/get", get_product, name="get-product"),
    path("products/create", create_product, name="create-product"),
    path("products/<int:id>/update", update_product, name="update-product"),
    path("departments/create", create_department, name="create-department"),
    path("departments/<int:id>/update", update_department, name="update-department"),
    path("employees/create", create_employee, name="create-employee"),
    path("employees/<int:id>/update", update_employee, name="update-employee"),
    path("users/get", get_users, name="get-users"),
    path("users/<int:id>/get", get_user, name="get-user"),
    path("users/create", create_user, name="create-user"),
    path("users/<int:id>/update", update_user, name="update-user"),
    path("books/get", get_books, name="get-books"),
    path("books/<int:id>/get", get_book, name="get-book"),
    path("books/create", create_book, name="create-book"),
    path("books/<int:id>/update", update_book, name="update-book"),
    path("books/create/many", create_books, name="create-books"),
    path("books/update/many", update_books, name="update-books"),
]
