# Generated by Django 5.0.1 on 2024-01-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serialization_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hexnut",
            name="hex_nut_small_thread_pitch_min_value",
        ),
        migrations.RemoveConstraint(
            model_name="hexnut",
            name="hex_nut_size_min_value",
        ),
        migrations.RemoveConstraint(
            model_name="hexnut",
            name="hex_nut_hight_min_value",
        ),
        migrations.RemoveConstraint(
            model_name="hexnut",
            name="hex_nut_e_min_value",
        ),
        migrations.RemoveConstraint(
            model_name="hexnut",
            name="hex_nut_mass_1000_pc_min_value",
        ),
        migrations.RemoveConstraint(
            model_name="hexnut",
            name="hex_nut_amout_pc_in_kg_min_value",
        ),
        migrations.AddConstraint(
            model_name="hexnut",
            constraint=models.CheckConstraint(
                check=models.Q(("small_thread_pitch__gte", 0.0)),
                name="hex_nut_small_thread_pitch_min_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="hexnut",
            constraint=models.CheckConstraint(
                check=models.Q(("size__gte", 0.0)), name="hex_nut_size_min_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="hexnut",
            constraint=models.CheckConstraint(
                check=models.Q(("hight__gte", 0.0)), name="hex_nut_hight_min_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="hexnut",
            constraint=models.CheckConstraint(
                check=models.Q(("e__gte", 0.0)), name="hex_nut_e_min_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="hexnut",
            constraint=models.CheckConstraint(
                check=models.Q(("mass_1000_pc__gte", 0.0)),
                name="hex_nut_mass_1000_pc_min_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="hexnut",
            constraint=models.CheckConstraint(
                check=models.Q(("amout_pc_in_kg__gte", 0.0)),
                name="hex_nut_amout_pc_in_kg_min_value",
            ),
        ),
    ]
