# Generated by Django 5.0.1 on 2024-02-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "serialization_app",
            "0002_remove_hexnut_hex_nut_small_thread_pitch_min_value_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=7, unique=True, verbose_name="Name"),
                ),
                (
                    "ip_address",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Ip address"
                    ),
                ),
                ("disk_capacity", models.FloatField(verbose_name="Disk capacity GiB")),
                ("ram", models.FloatField(verbose_name="RAM GiB")),
                ("cpu", models.FloatField(verbose_name="CPU GiB")),
                (
                    "serial_number",
                    models.CharField(
                        max_length=19, unique=True, verbose_name="Serial Number"
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Employee name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
        ),
    ]
