# Generated by Django 5.0.1 on 2024-02-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serialization_app", "0003_workstation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Address"
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Manager name",
                    ),
                ),
                (
                    "manager_number",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="Manager number",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FURNITURE", "FURNITURE"),
                            ("TOOL", "TOOL"),
                            ("HOUSEHOLD-APPLIANCE", "HOUSEHOLD-APPLIANCE"),
                        ],
                        max_length=255,
                        verbose_name="Category",
                    ),
                ),
                ("price", models.FloatField(default=0, verbose_name="Price")),
                (
                    "vendor_code",
                    models.CharField(
                        max_length=19, unique=True, verbose_name="Vendor code"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="serialization_app.store",
                        verbose_name="Store",
                    ),
                ),
            ],
        ),
    ]
