# Generated by Django 5.0.1 on 2024-03-01 03:44

import django.db.models.deletion
from django.db import migrations, models

import serialization_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("serialization_app", "0004_store_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "employees_number",
                    models.SmallIntegerField(verbose_name="Employees number"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Last name"),
                ),
                ("age", models.SmallIntegerField(verbose_name="Age")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        default=serialization_app.models.Department.get_default_id,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="employees",
                        to="serialization_app.department",
                        verbose_name="Department",
                    ),
                ),
            ],
        ),
    ]
